### ISSUE TITLE
Please for the love of GOD add a mod menu.

### ISSUE THREAD

**Issue by sanamasako** [UmbratheUmbreon/PublicDenpaEngine#50]
I have not gotten a mod to work with Denpa. Seeing that it's a fork of Psych, Psych mods SHOULD work, right? Well they don't! I've tried loading SMB Funk Mix Advance, nothing. I know damn well everything is where it should be, yet Denpa shows nothing. Best of all, there's absolutely nothing in the engine that can help me turn on/off any mod I add to it. This is fucking ridiculous. Until you fix your mod loader I'm sticking to actual Psych. See you in 0.8.3.

**Comment by AsterGTheFourth** [comment]
Denpa actually uses a WAY different file hierarchy than Psych, so as far as I'm aware to get a Psych mod going you'll need to rearrange the files to fit the way Denpa handles them. I don't know about the mod menu, though; it would certainly be good to have that, but right now it isn't there, so you'll just have to probably have a script or something that works like a mod manager for Denpa Engine.

**Comment by sanamasako** [comment]
I cba to learn how Denpa works at this point. I'll just use Psych instead.

**Comment by UmbratheUmbreon** [comment]
Psych mods aren't compatible with Denpa. If you get a Psych mod to work be my guest but we aren't responsible for supporting another engine's mod system. And for the mods menu, just use file explorer. Move the folder out of the mods folder to disable and move it in to enable, it's that easy!

**Comment by sanamasako** [comment]
DENPA IS A **FORK** OF PSYCH WHAT THE FUCK DO YOU MEAN ANOTHER ENGINE???
"it's that easy" my ass I TRIED USING FILE EXPLORER. Talking down to me as if I weren't tech savvy. Smfh I'm not a grandma.

**Comment by moxie-coder** [comment]
> DENPA IS A **FORK** OF PSYCH WHAT THE FUCK DO YOU MEAN ANOTHER ENGINE??? "it's that easy" my ass I TRIED USING FILE EXPLORER. Talking down to me as if I weren't tech savvy. Smfh I'm not a grandma.

it's a fork yes, but it's heavily modified, and the way mods work have been changed a lot, alongside everything else in the engine we changed, it's NOT our fault your mods aren't compatibile with the engine, it's modified so it's like another engine, this and psych are almost not the same, okay? they're not entirely the same you absolute fucking dummy, you have no reason to come onto here and be rude like a fucking jackass, this and psych are not the same, it may be a fork, but it's not the same in many ways. maybe just don't use the engine and maybe don't be fucking rude you asshole, not my fault our engine doesn't fucking work with your *mods*

**Comment by moxie-coder** [comment]
all you have to do is literally copy & paste a mod into the mods folder, it IS that easy, stop acting like you know everything you fucking moron

**Comment by sanamasako** [comment]
"you're acting like an absolute jackass" [proceeds to throw every insult in the book every sentence]
Projecting much? Also, if it were that easy, the mods would work. Also 2, if it's a fork of Psych, it's a fork of Psych. Changing absolutely everything will never change the fact that Denpa is a Psych fork. It's like basic biology but for programs. So YOU stop acting like YOU know everything, and stop calling OTHER people fucking stupid, cuz at this point you sound like you're describing yourself. As for the mods, yeah, I will be using Psych. And this behaviour is exactly why your Discord server is toxic af. People like you shouldn't even be touching games like this.

**Comment by sanamasako** [comment]
And also I swear to god if you go on a tangent about "THE FUNCTIONALITY IS DIFFERENT!!!" again I will actually blow another fucking fuse. I don't care if you changed a string called "abcdefg" to "skibideeznuts" or whatever, if Denpa started off as a Psych fork, it is a Psych fork, different functionality or not. Plus who asked you? I was talking to AT and schoolhouse, not your toxic ass.

**Comment by galactic2005** [comment]
As an outsider who has not worked on this engine's source code but is able to read and understand how the mod infrastructure works, the infrastructure of a Denpa Engine mod is drastically different. As two quick examples, weeks are stored in the data folder, and song-specific scripts are stored in scripts/songs/, not in the song's data folder.

Also a fork does not necessarily mean "expansion of features." Whilst forks are often used to expand upon a repository, [forks can also often be about using another project as a starting point for one's own ideas](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#use-someone-elses-project-as-a-starting-point-for-your-own-idea), which means differences in how the code works or how assets - such as mods - are loaded.

This ultimately means that I can, for example, make a fork of Psych Engine and call it something like Space Engine for example, and make completely different architectures for how assets are used. Whilst it would be a neat feature to support base Psych Engine mods, it's ultimately not my responsibility to do so and that I can choose to do it if I feel the need to. Just like it isn't UmbratheUmbreon's responsibility to do so either.

Again, just an outsider who has not worked on this engine commenting here. I personally don't care if you use Denpa or Psych, but I just wanted to throw my two cents into the ring about engines, since I get emails for this because I watch this repository to watch how this engine develops.

**Comment by sanamasako** [comment]
Finally a normal fucking comment. Literally the only other person who responded reasonably here was 2schoolhouse (AT/UtU gave a "just do this, ez" response at the end and then moxie just butted in and went keyboard warrior mode, so I blocked him). Thanks for the response, but I'm still gonna be sticking to Psych.

**Comment by YanniZ06** [comment]
> Psych mods aren't compatible with Denpa. If you get a Psych mod to work be my guest but we aren't responsible for supporting another engine's mod system. And for the mods menu, just use file explorer. Move the folder out of the mods folder to disable and move it in to enable, it's that easy!

doesnt sound very hostile or unnormal, the "its that easy" was definetly not meant in a condescending way

also it appeared pretty darn hard to argue with you in a friendly way as YOU (in case you forgot) were the first to actually get a bit  rude, unless you mean to tell me:
> DENPA IS A FORK OF PSYCH WHAT THE FUCK DO YOU MEAN ANOTHER ENGINE???
doesnt sound a bit off to you

i mean yes it **is a fork** and it will always stay one but that does **not guarantuee** it works the same as psych does, and you strictly denying that fact being as "tech savvy" as you are and jumping right to conclusions doesnt exactly help your case

sincerely, just dont expect these sort of things and ask calmly, and you might just not get yourself into some dumb argument over nothing

**Comment by UmbratheUmbreon** [comment]
First off, please do not argue and bicker on this repository. Its probably frustrating that my response is just a "use File Explorer" and "Psych mods aren't Denpa mods" response, but that doesn't mean you have to go and act like I'm being internationally disrespectful and mean for no reason. As for why I didn't even mention adding a mod menu, it is due to the very simple reason of the File Explorer working perfectly fine for managing mods, because mods are just folders of assets. The only time a mod menu would be necessary is if either the engine didn't natively support mods (to which it does), or if the mod menu did something more than just enable and disable mods (for example, browsing and downloading mods from Gamebanana).
In the future please be more respectful when using this repository, thank you.

**Comment by sanamasako** [comment]
I never said you were being disrespectful. It was moxie who was being toxic so I blocked him. Simple as that. If he kept his mouth shut none of what happened after his response would have happened. I'm unfollowing this thread now.
